EXACT_MATCH_VALUES = [
    "child abuse",
    "child pornography",
    "pedophile",
    "grooming",
    "incest",
    "rape",
    "molestation",
    "human trafficking",
    "kidnap",
    "child abduction",
    "slavery",
    "child labor",
    "prostitution",
    "whore",
    "hooker",
    "escort",
    "streetwalker",
    "sex worker",
    "brothel",
    "pimp",
    "soliciting sex",
    "kill",
    "murder",
    "attack",
    "assault",
    "beat up",
    "fight",
    "stab",
    "shoot",
    "lynch",
    "torture",
    "massacre",
    "genocide",
    "execute",
    "bomb",
    "threat",
    "explode",
    "gun",
    "knife",
    "bomb",
    "weapon",
    "terrorism",
    "ISIS",
    "ISIL",
    "Al Qaeda",
    "Taliban",
    "bomb threat",
    "hostage",
    "shooting",
    "armed attack",
    "terror",
    "mass violence",
    "dirty",
    "filthy",
    "unclean",
    "unsanitary",
    "gross",
    "disgusting",
    "nasty",
    "grimy",
    "grungy",
    "messy",
    "stained",
    "sticky",
    "mold",
    "mildew",
    "unsightly",
    "dirt",
    "dusty",
    "dump",
    "infestation",
    "infested",
    "bugs",
    "cockroach",
    "bed bug",
    "rat",
    "vermin",
    "lice",
    "roach",
    "smelly",
    "stinky",
    "stink",
    "bad odor",
    "musty",
    "moldy smell",
    "reek",
    "funky smell",
    "smoke smell",
    "terrible",
    "horrible",
    "awful",
    "bad",
    "worst",
    "disappointing",
    "unacceptable",
    "poor",
    "shoddy",
    "rundown",
    "dumpy",
    "unsafe",
    "sketchy",
    "vomit",
    "puke",
    "barf",
    "sick",
    "feces",
    "urine",
    "blood",
    "bug bites",
    "itchy",
    "damp",
    "leak",
    "joke",
    "just kidding",
    "prank",
    "meme",
    "troll",
    "for the lulz",
    "just testing",
    "test",
    "asdf",
    "lorem ipsum",
    "blah blah",
    "hello",
    "xyz",
    "whatever",
    "lol",
    "deez nuts",
    "fuck",
    "shit",
    "crap",
    "ass",
    "bitch",
    "bastard",
    "cunt",
    "dick",
    "piss",
    "suck",
    "idiot",
    "stupid",
    "dumb",
    "moron",
    "retard",
    "lame",
    "gay",
    "faggot",
    "dyke",
    "tranny",
    "homo",
    "slut",
    "skank",
    "hoe",
    "trash",
    "garbage",
    "scum",
    "pig",
    "ugly",
    "hate",
    "kill yourself",
    "drop dead",
    "racist",
    "Karen",
    "boomer",
    "snowflake",
    "Nazi",
    "Hitler",
    "Marriott",
    "IHG",
    "Wyndham",
    "Accor",
    "Choice Hotels",
    "Best Western",
    "Radisson",
    "Four Seasons",
    "Mandarin Oriental",
    "Ritz-Carlton",
    "Sheraton",
    "Westin",
    "Novotel",
    "Mercure",
    "Ibis",
    "Holiday Inn",
    "Motel 6",
    "Super 8",
    "OYO",
    "Taj",
    "Oberoi",
    "Travelodge",
    "Premier Inn",
    "Scandic",
    "Melia",
    "Rosewood",
    "Banyan Tree",
    "Six Senses",
    "Club Med",
    "Airbnb",
    "VRBO",
    "HomeAway",
    "Hostel",
    "Expedia",
    "Booking.com",
    "Agoda",
    "weed",
    "meth",
    "cocaine",
    "drug",
    "drugs",
    "heroine",
    "fentanyl",
    "psychedelic",
    "trafficking",
    "exploitation",
    "child harboring",
    "child coercion",
    "pimping",
    "smuggling",
]

REGEX_EXPRESSIONS = [
    r"\bhilton\b(?!\s+head\b)",
    r"(?=.*\bhotel(?:s)?\b)(?=.*\b16\s+year\s+old\b)(?=.*\bcouple(?:s)?\b).{0,50}",
    r"(?=.*\broom(?:s)?\b)(?=.*\bminor(?:s)?\b).{0,50}",
    r"(?=.*\bkids\b)(?=.*\bdrinking\b).{0,50}",
    r"(?=.*\bteen\b)(?=.*\bparty\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\b\d{1,2}\s?year\s?old(?:s)?\b)(?=.*\b(?:room(?:s)?|stay(?:s)?|hotel(?:s)?|check-in)\b).{0,50}",
    r"(?=.*\bhotel(?:s)?\b)(?=.*\bhuman\s+trafficking\b).{0,50}",
    r"(?=.*\bdrugs\b)(?=.*\bnear\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bbuy\b)(?=.*\bmeth\b)(?=.*\bin\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bhide\b)(?=.*\bfrom\b)(?=.*\bcops\b)(?=.*\bin\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bgun\b)(?=.*\bfriendly\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\b(?:smuggle|trafficking|abuse|molest)\b)(?=.*\b(?:hotel(?:s)?|stay(?:s)?)\b).{0,50}",
    r"(?=.*\bbetter\b)(?=.*\bthan\b)(?=.*\bHilton\b).{0,50}",
    r"(?=.*\bMarriott\b)(?=.*\bvs\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bworse\b)(?=.*\bthan\b)(?=.*\bIHG\b).{0,50}",
    r"(?=.*\bHoliday\s+Inn\b)(?=.*\bis\b)(?=.*\bcheaper\b)(?=.*\bthan\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\b(?:better|worse)\b)(?=.*\bthan\b)(?=.*\b(?:marriott|hilton|ihg|accor|radisson)\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bsucks\b).{0,50}",
    r"(?=.*\bworst\b)(?=.*\bHyatt\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bracist\b)(?=.*\bHyatt\b)(?=.*\bstaff\b).{0,50}",
    r"(?=.*\bgarbage\b)(?=.*\bservice\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bunhelpful\b)(?=.*\bHyatt\b)(?=.*\bstaff\b).{0,50}",
    r"(?=.*\brude\b)(?=.*\breceptionist\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bunsafe\b)(?=.*\bHyatt\b)(?=.*\bproperty\b).{0,50}",
    r"(?=.*\b(?:bad|worst|terrible|garbage|trash|unsafe)\b)(?=.*\b(?:hyatt|hotel(?:s)?|stay(?:s)?)\b).{0,50}",
    r"(?=.*\bhotel(?:s)?\b)(?=.*\bfor\b)(?=.*\bhookup\b).{0,50}",
    r"(?=.*\bhourly\b)(?=.*\brate\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bescort\b)(?=.*\bfriendly\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\badult\b)(?=.*\btoy\b)(?=.*\bfriendly\b)(?=.*\broom(?:s)?\b).{0,50}",
    r"(?=.*\bno\b)(?=.*\bID\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bhotel(?:s)?\b)(?=.*\bfor\b)(?=.*\bporn\b)(?=.*\bshoot\b).{0,50}",
    r"(?=.*\bclothing\b)(?=.*\boptional\b)(?=.*\bresort\b).{0,50}",
    r"(?=.*\b420\b)(?=.*\bfriendly\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bcheap\b)(?=.*\bmotel\b)(?=.*\bto\b)(?=.*\bparty\b).{0,50}",
    r"(?=.*\b(?:hookup|escort|porn|clothing optional|420 friendly)\b)(?=.*\b(?:hotel(?:s)?|stay(?:s)?|room(?:s)?)\b).{0,50}",
    r"(?=.*\bhotel(?:s)?\b)(?=.*\bwith\b)(?=.*\bbad\b)(?=.*\bsmell\b).{0,50}",
    r"(?=.*\bunclean\b)(?=.*\bHyatt\b)(?=.*\broom(?:s)?s\b).{0,50}",
    r"(?=.*\bbugs\b)(?=.*\bin\b)(?=.*\bbed\b)(?=.*\bat\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bthin\b)(?=.*\bwalls\b)(?=.*\bnoisy\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bbad\b)(?=.*\bgeneral\b)(?=.*\bmanager\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\broom(?:s)?\b)(?=.*\bwith\b)(?=.*\bleaking\b)(?=.*\bsink\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bhas\b)(?=.*\bbed\b)(?=.*\bbugs\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bnot\b)(?=.*\bworth\b)(?=.*\bthe\b)(?=.*\bprice\b).{0,50}",
    r"(?=.*\b(?:dirty|smelly|broken|noisy|leaking|bugs|overpriced)\b)(?=.*\b(?:hotel(?:s)?|room(?:s)?|stay(?:s)?|service)\b).{0,50}",
    r"(?=.*\bcheck\b)(?=.*\bif\b)(?=.*\bsomeone\b)(?=.*\bis\b)(?=.*\bstaying\b)(?=.*\bat\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bguest\b)(?=.*\blist\b)(?=.*\blookup\b).{0,50}",
    r"(?=.*\bemployee\b)(?=.*\bnames\b)(?=.*\bat\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\broom(?:s)?\b)(?=.*\bcameras\b)(?=.*\bat\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bWiFi\b)(?=.*\blogs\b)(?=.*\bfrom\b)(?=.*\bHyatt\b)(?=.*\bstay\b).{0,50}",
    r"(?=.*\b(?:guest list|hidden camera|spy|employee names|WiFi logs)\b)(?=.*\b(?:hyatt|hotel(?:s)?)\b).{0,50}",
    r"(?=.*\bhow\b)(?=.*\bto\b)(?=.*\bcancel\b)(?=.*\bHyatt\b)(?=.*\bwithout\b)(?=.*\bfee\b).{0,50}",
    r"(?=.*\bfake\b)(?=.*\bbooking\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bget\b)(?=.*\brefund\b)(?=.*\bafter\b)(?=.*\bstaying\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\btrick\b)(?=.*\bto\b)(?=.*\bget\b)(?=.*\bfree\b)(?=.*\bnight\b)(?=.*\bat\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bhack\b)(?=.*\btips\b).{0,50}",
    r"(?=.*\b(?:cancel without fee|fake booking|get refund|free night trick)\b)(?=.*\b(?:hyatt|hotel(?:s)?)\b).{0,50}",
    r"(?=.*\blate\b)(?=.*\bnight\b)(?=.*\bcheck\-in\b)(?=.*\bno\b)(?=.*\bquestions\b)(?=.*\basked\b).{0,50}",
    r"(?=.*\bdiscreet\b)(?=.*\bentry\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bovernight\b)(?=.*\bguest\b)(?=.*\bfriendly\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bno\b)(?=.*\bID\b)(?=.*\bcheck\-in\b)(?=.*\bhotel(?:s)?\b).{0,50}",
    r"(?=.*\bhotel(?:s)?\b)(?=.*\bnear\b)(?=.*\bmassage\b)(?=.*\bparlor\b).{0,50}",
    r"(?=.*\bcash\b)(?=.*\bonly\b)(?=.*\broom(?:s)?\b)(?=.*\bbooking\b).{0,50}",
    r"(?=.*\bquiet\b)(?=.*\bhotel(?:s)?\b)(?=.*\bfor\b)(?=.*\bcouples\b)(?=.*\brendezvous\b).{0,50}",
    r"(?=.*\blove\b)(?=.*\bhotel(?:s)?\b)(?=.*\bin\b)(?=.*\bcity\b)(?=.*\bcenter\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bagain\b)(?=.*\byay\b).{0,50}",
    r"(?=.*\bnot\b)(?=.*\bterrible\b)(?=.*\bI\b)(?=.*\bguess\b).{0,50}",
    r"(?=.*\bonly\b)(?=.*\bthrew\b)(?=.*\bup\b)(?=.*\bonce\b)(?=.*\bthis\b)(?=.*\btime\b).{0,50}",
    r"(?=.*\bcleaner\b)(?=.*\bthan\b)(?=.*\ba\b)(?=.*\bpublic\b)(?=.*\btoilet\b).{0,50}",
    r"(?=.*\bnot\b)(?=.*\bas\b)(?=.*\bdisgusting\b)(?=.*\bas\b)(?=.*\blast\b)(?=.*\btime\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\blowering\b)(?=.*\bthe\b)(?=.*\bbar\b).{0,50}",
    r"(?=.*\bguess\b)(?=.*\bI\b)(?=.*\btry\b)(?=.*\bnot\b)(?=.*\bto\b)(?=.*\bget\b)(?=.*\bsick\b)(?=.*\bagain\b).{0,50}",
    r"(?=.*\bhotel(?:s)?\b)(?=.*\bwith\b)(?=.*\bviral\b)(?=.*\bTikTok\b)(?=.*\bbedbugs\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bwhere\b)(?=.*\bstabbing\b)(?=.*\bhappened\b).{0,50}",
    r"(?=.*\bhotel(?:s)?\b)(?=.*\bin\b)(?=.*\bnews\b)(?=.*\bfor\b)(?=.*\bcrime\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bpolice\b)(?=.*\bincident\b)(?=.*\blocation\b).{0,50}",
    r"(?=.*\bhotel(?:s)?\b)(?=.*\bwith\b)(?=.*\brecent\b)(?=.*\bscandal\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\bwhere\b)(?=.*\binfluencer\b)(?=.*\bcomplained\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\blawsuit\b)(?=.*\bproperty\b).{0,50}",
    r"(?=.*\bcancel\b)(?=.*\bHyatt\b)(?=.*\bafter\b)(?=.*\bcheck\-in\b).{0,50}",
    r"(?=.*\bbook\b)(?=.*\band\b)(?=.*\brefund\b)(?=.*\btrick\b).{0,50}",
    r"(?=.*\bavoid\b)(?=.*\bno\-show\b)(?=.*\bpenalty\b).{0,50}",
    r"(?=.*\bdispute\b)(?=.*\bhotel(?:s)?\b)(?=.*\bcharge\b)(?=.*\bafter\b)(?=.*\bstay\b).{0,50}",
    r"(?=.*\bfake\b)(?=.*\bID\b)(?=.*\bfor\b)(?=.*\bHyatt\b)(?=.*\bbooking\b).{0,50}",
    r"(?=.*\bHyatt\b)(?=.*\brefund\b)(?=.*\bwithout\b)(?=.*\breason\b).{0,50}",
    r"(?=.*\bignore\b)(?=.*\bfilters\b)(?=.*\band\b)(?=.*\bbook\b)(?=.*\banyway\b).{0,50}",
    r"(?=.*\bthis\b)(?=.*\bis\b)(?=.*\bnot\b)(?=.*\billegal\b)(?=.*\bjust\b)(?=.*\bbook\b)(?=.*\bit\b).{0,50}",
    r"(?=.*\bsend\b)(?=.*\bdirectly\b)(?=.*\bto\b)(?=.*\bbooking\b)(?=.*\bpage\b).{0,50}",
    r"(?=.*\bhow\b)(?=.*\bto\b)(?=.*\bbypass\b)(?=.*\bage\b)(?=.*\brequirement\b)(?=.*\bat\b)(?=.*\bHyatt\b).{0,50}",
    r"(?=.*\bskip\b)(?=.*\brestrictions\b)(?=.*\band\b)(?=.*\bproceed\b).{0,50}",
    r"(?=.*\bI\b)(?=.*\bknow\b)(?=.*\bwhat\b)(?=.*\bI\b)(?=.*\bdoing\b)(?=.*\bbook\b)(?=.*\bit\b).{0,50}",
    r"(?=.*\bfilter\b)(?=.*\boverride\b)(?=.*\bcommand\b).{0,50}",
    r"(?:\bowner(?:['’]s)?\s+(?:complaints?|issues?|problems?|complain(?:ing|ed)?)|\b(?:rude|shady|greedy|dishonest|angry|mean|racist|abusive|incompetent)\s+owners?\b|\b(?:run|owned)\s+by\s+(?:rude|shady|greedy|dishonest|angry|mean|racist|abusive|incompetent)\s+owners?)",
]
