EXACT_MATCH_VALUES = [
    "Jiuzhai Valley National Park, Jiuzhaigou County, Ngawa Tibetan and Qiang Autonomous Prefecture, Sichuan, China",
    "Ho Chi Minh City, Ho-Chi-Minh-City, VN",
    "Ho-Chi-Minh-City, VN",
    "Ho-Chi-Minh-City VN",
    "Ho Chi Minh City, Ho-Chi-Minh-City",
    "Ho Chi Minh City Ho-Chi-Minh-City",
    "Orlando International Airport (MCO), Jeff Fuqua Boulevard, Orlando, FL, USA",
    "Ningbo, China",
    "Izmir, Türkiye",
    "White Plains, New York, United States",
    "Fuzhou, China",
    "Türkiye",
    "Turkiye",
    "NRG Stadium, NRG Parkway, Houston, TX, USA",
    "White Salmon, Washington, United States",
    "Chincoteague Island, Chincoteague, VA, USA",
    "White Plains, New York, USA",
    "Whitehorse, Yukon, Canada",
    "White City, Oregon, USA",
    "Whitehaven, Cumbria, UK",
    "White River, Mpumalanga, South Africa",
    "White Sands, New Mexico, USA",
    "Whitefield, Manchester, UK",
    "Whitehall, Montana, USA",
    "Whitehall, Pennsylvania, USA",
    "Whitehall, London, UK",
    "Blackpool, England",
    "Black Forest, Germany",
    "Black Hawk, Colorado, USA",
    "Black Mountain, North Carolina, USA",
    "Blackheath, London, UK",
    "Black River, Jamaica",
    "Black River, Mauritius",
    "Blackburn, UK",
    "Red Bank, New Jersey, USA",
    "Redmond, Washington, USA",
    "Red River, New Mexico, USA",
    "Red River, Canada",
    "Redding, California, USA",
    "Redhill, UK",
    "Blue Mountains, Australia",
    "Bluefield, West Virginia, USA",
    "Blue Ash, Ohio, USA",
    "Blue Lake, California, USA",
    "Brownsville, Texas, USA",
    "Browns Bay, Auckland, New Zealand",
    "Brown Deer, Wisconsin, USA",
    "Dildo, Newfoundland, Canada",
    "Intercourse, Pennsylvania, USA",
    "Hell, Michigan, USA",
    "Bastardstown, Wexford, Ireland",
    "Middelfart, Denmark",
    "Titisee-Neustadt, Germany",
    "Shitterton, Dorset, UK",
    "Muff, Ireland",
    "Bald Knob, Arkansas, USA",
    "Climax, Michigan, USA",
    "Climax, Georgia, USA",
    "Climax, Saskatchewan, Canada",
    "Kill, County Kildare, Ireland",
    "Gun Barrel City, Texas, USA",
    "Battle Creek, Michigan, USA",
    "Knife River, Minnesota, USA",
    "Skull Valley, Utah, USA",
    "Cut and Shoot, Texas, USA",
    "Slaughter Beach, Delaware, USA",
    "Gore, New Zealand",
    "Gore, Oklahoma, USA",
    "white plains",
    "Kigali, Kigali, RW",
    "Sofia, Sofia-Capital, BG",
    "Buenos Aires, Buenos-Aires-F-D-, AR",
    "Nadi, Western, FJ",
    "izmir, Turkiye",
    "Cumming, GA, USA",
    "Killarney, County Kerry, Ireland",
    "Ayala Park, Central Avenue, Chino, CA, USA",
    "Ambassador House Condominium, North State Parkway, Chicago, IL, USA",
    "NRG Park, NRG Parkway, Houston, TX, USA",
    "Nags Head, NC, USA",
    "White Plains, NY, USA",
    "Whitehorse, Canada",
    "dolomites",
    "7135 East Camelback Road, Scottsdale",
    "Can Tho, Ninh Kiều, Cần Thơ, Vietnam",
    "Chang Bai Shan, Fusong County, Baishan, China",
    "Cixi, Ningbo, Zhejiang, China",
    "Hangzhou aitport",
    "Hangzhou airport",
    "Hyatt Centric hongkong",
    "Hyatt Place Sukhum",
    "Hyatt fushan",
    "Isleta Amphitheater, University Boulevard Southeast, Albuquerque, NM, USA",
    "MIDFLORIDA Credit Union Amphitheatre, U.S. 301, Tampa, FL, USA",
    "Nrg stadium",
    "Lima Airport (LIM), Avenida Elmer Faucett, Callao, Peru",
    "Boomer, North Carolina, USA",
    "El nido",
    "The Nashville Palace, McGavock Pike, Nashville, TN, USA",
    "Fuquay-Varina, NC, USA",
    "Gay Village, Ville-Marie, Montreal, QC, Canada",
    "Gay Village, Ville-Marie, Montréal, QC, Canada",
    "El Nido, Palawan, Philippines",
    "Dickies Arena, Montgomery Street, Fort Worth, TX, USA",
    "Dumbo, Brooklyn, NY, USA",
    "Dumbo broklyn",
    "American Family Insurance Amphitheater, North Harbor Drive, Milwaukee, WI, USA",
    "Crocker Park, Crocker Park Boulevard, Westlake, Ohio, USA",
    "Accor Arena, Boulevard de Bercy, Paris, France",
    "take my family to the mountains",
    "Golder nugget tahoe",
    "Klanath falls",
    "Hilton head sc",
    "Park hyatt ningbo",
    "Hunt Valley, Cockeysville, MD, USA",
    "Leak & Sons Funeral Homes",
    "Hyatt centric hong kong",
    "Segerstrom Center for the Arts",
    "Tahoe Group, South Wacker Drive, Chicago, IL, USA",
    "Whitsundays QLD, Australia",
    "Yin Chuan, Ningxia, China",
    "grand hyatt bgc",
    "Nosy Be, Madagascar",
    "81 West White Horse Pike Berlin",
    "Blind Tiger Portland",
    "Buckhead",
    "Chincoteague",
    "MIDFLORIDA Credit Union Amphitheatre",
    "Hyatt Place Bangkok Sukhumvit",
    "Ambdassador House Condominium",
    "Hyatt regency ningbo",
    "Ningxia, China",
    "Whitsundays, Australia",
    "Nacogdoches, TX, USA",
    "Turkistan",
    "Tabuk Saudi Arabia",
    "Kill Devil Hills, NC, USA",
    "Mount Washington",
    "Hyatt Centric Hong Kong",
    "10505 nw 36th st, miami, florida, usa",
    "1205 sheldon cove bldg 3, austin, tx 78753, usa",
    "1205 sheldon cove, bldg 3, austin, tx 78753",
    "137 knickerbocker ave paterson nj 07503",
    "137 knickerbocker ave, paterson, nj 07503, usa",
    "3663 bullhead pkwy, bullhead city, az 86442, usa",
    "45 whitechapel road, london, uk",
    "601 f st nw, washington, dc, usa",
    "airbnb hq, brannan street, san francisco, ca, usa",
    "atlanta buckhead",
    "bad nauheim, germany",
    "buckhead",
    "bull and last",
    "bullhead city, az 86442, usa",
    "bullhead city, az, usa",
    "camelback mountain, phoenix, az, usa",
    "camelback ranch - glendale, west camelback road, phoenix, az, usa",
    "caramel valley ramch",
    "central park amphitheater, iroquois ln, schenectady, new york, usa",
    "curacao dreams travel b.v., playa westpunt, willemstad, curasao",
    "effingham, il, usa",
    "fish kill, new york, usa",
    "fu zhou, fujian, china",
    "fukuoka airport (fuk), 778-1 shimousui, hakata ward, fukuoka, japan",
    "fulda",
    "gch craftsman grill, disneyland drive, anaheim, ca, usa",
    "gct, lexington avenue, nyc, ny, usa",
    "gijang-gun, busan, south korea",
    "grand canyon university, west camelback road, phoenix, az, usa",
    "grand hyatt buckhead",
    "grand hyatt indian",
    "grand hyattt buckhead",
    "henan china gongfutuan, zhongyuan west road, zhongyuan district, zhengzhou, henan, china",
    "hill country texas",
    "holston house",
    "how to gwt to hyatt cap cana",
    "hyatt place colorado spings hotel 201 e. kiowa",
    "hyatt regency 9300 jeff fuqua blvd",
    "hyatt regency ho chi migh",
    "hyatt rgency dubai",
    "inn of the white salmon, west jewett boulevard, white salmon, wa, usa",
    "kemah boardwalk, kipp avenue, kemah, tx, usa",
    "kips bay ny",
    "lee road, valley, fh67+ff, spanish town vg1150, british virgin islands",
    "lumen field",
    "lumen field parking, seattle, wa, usa",
    "lumen field, occidental avenue south, seattle, wa, usa",
    "ningbo, zhejiang, cn",
    "orlando northface outlets",
    "pingtan, fuzhou, fujian, china",
    "polluck pines",
    "sjo oasis hostel, avenida 14, san jose, pacifio, costa rica",
    "tcu hyatt",
    "turks",
    "voco seoul gangnam by ihg, dosan-daero",
    "westin",
    "while you are here",
    "white marsh, md, usa",
    "whitestown, in, usa",
    "whitsundays qld, australia",
    "woods hole, falmouth, ma, usa",
    "NRG Center, Fannin Street, Houston, TX, USA",
]

REGEX_EXPRESSIONS = []
